name: Tests

on: [push, pull_request]

env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction"
  CC_TEST_REPORTER_ID: 6c949df7fff56bf563fa7e731c22af7f3709413f2fa601e970fac088744e76ee
jobs:
  ## PHPSTAN
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@2.21.0
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          update: true
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: PHPStan tests
        run: composer phpstan

  ## Rector
  rector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@2.21.0
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          update: true
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader
      - name: Rector tests
        run: composer rector
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply rector changes
        
  ## PHPCSFIXER
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install
          run: composer install
        - name: Run php-cs-fixer
          run: composer phpcsfixer
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
              commit_message: Apply php-cs-fixer changes

  ## PHPUNIT
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', '8.1', '8.2']

    steps:
      ## checkout the repoistory 
      - name: Checkout Repo
        uses: actions/checkout@v3

      ## Install(?) php
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: apc, curl, dom, imagick, intl, mbstring, mcrypt, memcached, mysql, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, sqlite
          ini-values: date.timezone='UTC'

      ## install composer
      - name: Install dependencies
        run: composer install $DEFAULT_COMPOSER_FLAGS

      ## run unit tests
      - name: PHP Unit tests for PHP 
        run: vendor/bin/phpunit --configuration actions.phpunit.xml
        if: matrix.php == '8.2' || matrix.php == '8.1'

      ## unit test with coverage
      - name: PHP Unit tests for PHP 8.0
        run: vendor/bin/phpunit --coverage-clover=clover.xml --configuration actions.phpunit.xml
        if: matrix.php == '8.0'

      ## coverage
      - name: Code coverage
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter after-build -t clover
        if: matrix.php == '8.0'
        continue-on-error: true # if is fork
